version: "3.9"
services:

  database:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    working_dir: /app
    env_file:
        - ".env"
    environment:
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
        - "3306:3306"
    depends_on:
        - php-fpm
    volumes:
      - /data/db/mysql:/var/lib/mysql
    networks:
      dataprag:
        aliases:
          - "db.docker"

  webserver:
    image: nginx:alpine
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:8000"
    networks:
      dataprag:

  php-fpm:
    build: ./docker/php-fpm
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
    networks:
      dataprag:

volumes:
  database:

networks:
  dataprag:
